version: '3'

services:
  postgresql:
    image: postgres:14
    container_name: dbt-pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbt
      - POSTGRES_PASSWORD=dbt
      - POSTGRES_DB=dbt
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
  graphql-engine:
    image: hasura/graphql-engine:v2.3.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgresql"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://dbt:dbt@postgresql:5432/hasura
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      PG_DATABASE_URL: postgres://dbt:dbt@postgresql:5432/dbt
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
