version: '3'

services:
  postgresql:
    image: postgres
    container_name: dbt-pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbt
      - POSTGRES_PASSWORD=dbt
      - POSTGRES_DB=dbt
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always
